import = [ "~/.config/alacritty/theme.toml", "~/.config/alacritty/font.toml", "~/.local/share/omakub/defaults/alacritty.toml" ]

[font]
size = 12

[selection]
save_to_clipboard = true

[window]
startup_mode = "SimpleFullscreen"
